version: "3.3"
services:
  latex:
    build: .
    # image: pytorch/pytorch:latest
    container_name: socialways
    volumes:
      - type: bind
        source: "$PWD/../"
        target: /home
    stdin_open: true
    tty: true
